version: '3.5'

services:

  steam_games_spider:
    build:
      context: .
      dockerfile: dockerfile
    container_name: steam_games_spider
    image: docker.ziliplay.com/steam_games_spider:1.0
    networks:
      - spider_steam_games_network
    volumes:
      - ./src:/app:rw
      - ~/spider/steam_img:/app/static/steam_img:rw
    env_file: dev.env
    tty: true

  #### BEGIN SPIDER SEVERS ####

networks:
  spider_steam_games_network:
    external:
      name: spider_network
